Reland add FeatureProvider for SyncAcrossDevices Settings integration.
Prior CL ag/26930404 was reverted because an unused class was
trimmed in AOSP, causing test cases to throw NoClassDefFoundError
exceptions. This CL combines ag/26930404 and ag/26995936 to address
the failure.

Bug: 330498032
Test: atest FakeFeatureFactory, atest SyncAcrossDevicesPreferenceControllerTest
Change-Id: I0a7ebccdebcad20e06d7542d7c4a0005885f393b

Former-commit-id: 5f391359e33975ea6f52f241ac81dd7900799df9